name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clone private repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://x-access-token:${GH_PAT}@github.com/SwarmingTeapots/CompanyLandingPage.git

      - name: Install dependencies
        working-directory: ./CompanyLandingPage
        run: |
          npm i

      - name: Build landing site
        working-directory: ./CompanyLandingPage
        run: |
          npm run build

      - name: Publish to Cloudflare Workers from private repo
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.18.0"
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./CompanyLandingPage
